-- BEGIN SYNCED MIGRATION: 20260922_financial_exception_workflow.sql
CREATE TABLE IF NOT EXISTS public.financial_exception_cases(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),source_type TEXT NOT NULL CHECK(source_type IN('RECONCILIATION','TRANSACTION','SETTLEMENT','PROVIDER','TREASURY','MERCHANT','AGENT')),source_id TEXT NOT NULL,
 organization_id UUID REFERENCES public.organizations(id) ON DELETE RESTRICT,severity TEXT NOT NULL CHECK(severity IN('LOW','MEDIUM','HIGH','CRITICAL')),category TEXT NOT NULL,title TEXT NOT NULL,details JSONB NOT NULL DEFAULT '{}',
 status TEXT NOT NULL DEFAULT 'OPEN' CHECK(status IN('OPEN','ASSIGNED','PENDING_APPROVAL','RESOLVED','REJECTED','ESCALATED')),assigned_to TEXT,assigned_by TEXT,assigned_at TIMESTAMPTZ,
 sla_due_at TIMESTAMPTZ NOT NULL,escalated_at TIMESTAMPTZ,resolution_request_id UUID,resolved_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(source_type,source_id,category)
);
CREATE TABLE IF NOT EXISTS public.financial_exception_resolution_requests(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),case_id UUID NOT NULL REFERENCES public.financial_exception_cases(id) ON DELETE RESTRICT,requested_by TEXT NOT NULL,reviewed_by TEXT,
 disposition TEXT NOT NULL CHECK(disposition IN('FALSE_POSITIVE','RECONCILED','REVERSED','REPAIRED','ACCEPTED_RISK','REFERRED')),summary TEXT NOT NULL,evidence JSONB NOT NULL,
 status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','APPROVED','REJECTED','EXPIRED')),review_reason TEXT,expires_at TIMESTAMPTZ NOT NULL DEFAULT(NOW()+INTERVAL '24 hours'),reviewed_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_exception_open_resolution ON public.financial_exception_resolution_requests(case_id) WHERE status='PENDING';
CREATE INDEX IF NOT EXISTS idx_fin_exception_queue ON public.financial_exception_cases(status,severity,sla_due_at);
ALTER TABLE public.financial_exception_cases ENABLE ROW LEVEL SECURITY;ALTER TABLE public.financial_exception_resolution_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS financial_exception_cases_service ON public.financial_exception_cases;DROP POLICY IF EXISTS financial_exception_resolutions_service ON public.financial_exception_resolution_requests;
CREATE POLICY financial_exception_cases_service ON public.financial_exception_cases FOR ALL TO service_role USING(TRUE) WITH CHECK(TRUE);CREATE POLICY financial_exception_resolutions_service ON public.financial_exception_resolution_requests FOR ALL TO service_role USING(TRUE) WITH CHECK(TRUE);
REVOKE ALL ON public.financial_exception_cases,public.financial_exception_resolution_requests FROM anon,authenticated;GRANT SELECT,INSERT ON public.financial_exception_cases,public.financial_exception_resolution_requests TO service_role;

CREATE OR REPLACE FUNCTION public.open_financial_exception_v1(p_source_type TEXT,p_source_id TEXT,p_organization_id UUID,p_severity TEXT,p_category TEXT,p_title TEXT,p_details JSONB)
RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_id UUID;v_severity TEXT:=UPPER(BTRIM(p_severity));v_source TEXT:=UPPER(BTRIM(p_source_type));
BEGIN IF v_source NOT IN('RECONCILIATION','TRANSACTION','SETTLEMENT','PROVIDER','TREASURY','MERCHANT','AGENT') OR v_severity NOT IN('LOW','MEDIUM','HIGH','CRITICAL') OR LENGTH(BTRIM(COALESCE(p_source_id,'')))<1 OR LENGTH(BTRIM(COALESCE(p_category,'')))<3 OR LENGTH(BTRIM(COALESCE(p_title,'')))<5 THEN RAISE EXCEPTION 'FINANCIAL_EXCEPTION_INVALID';END IF;
 INSERT INTO public.financial_exception_cases(source_type,source_id,organization_id,severity,category,title,details,sla_due_at) VALUES(v_source,BTRIM(p_source_id),p_organization_id,v_severity,UPPER(BTRIM(p_category)),BTRIM(p_title),COALESCE(p_details,'{}'),NOW()+CASE v_severity WHEN 'CRITICAL' THEN INTERVAL '15 minutes' WHEN 'HIGH' THEN INTERVAL '2 hours' WHEN 'MEDIUM' THEN INTERVAL '8 hours' ELSE INTERVAL '24 hours' END) ON CONFLICT(source_type,source_id,category) DO UPDATE SET details=financial_exception_cases.details||EXCLUDED.details,severity=CASE WHEN array_position(ARRAY['LOW','MEDIUM','HIGH','CRITICAL'],EXCLUDED.severity)>array_position(ARRAY['LOW','MEDIUM','HIGH','CRITICAL'],financial_exception_cases.severity) THEN EXCLUDED.severity ELSE financial_exception_cases.severity END,updated_at=NOW() RETURNING id INTO v_id;RETURN v_id;END$$;
CREATE OR REPLACE FUNCTION public.assign_financial_exception_v1(p_actor_id TEXT,p_case_id UUID,p_assignee_id TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_case public.financial_exception_cases%ROWTYPE;BEGIN IF NOT public.audit_export_officer_v1(p_actor_id) OR NOT public.audit_export_officer_v1(p_assignee_id) THEN RAISE EXCEPTION 'FINANCIAL_EXCEPTION_ASSIGNMENT_DENIED';END IF;SELECT * INTO v_case FROM public.financial_exception_cases WHERE id=p_case_id FOR UPDATE;IF NOT FOUND OR v_case.status IN('RESOLVED','REJECTED') THEN RAISE EXCEPTION 'FINANCIAL_EXCEPTION_NOT_ASSIGNABLE';END IF;UPDATE public.financial_exception_cases SET assigned_to=p_assignee_id,assigned_by=p_actor_id,assigned_at=NOW(),status='ASSIGNED',updated_at=NOW() WHERE id=p_case_id;RETURN jsonb_build_object('case_id',p_case_id,'status','ASSIGNED','assigned_to',p_assignee_id);END$$;
CREATE OR REPLACE FUNCTION public.request_financial_exception_resolution_v1(p_actor_id TEXT,p_case_id UUID,p_disposition TEXT,p_summary TEXT,p_evidence JSONB)
RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_case public.financial_exception_cases%ROWTYPE;v_id UUID;BEGIN SELECT * INTO v_case FROM public.financial_exception_cases WHERE id=p_case_id FOR UPDATE;IF NOT FOUND OR v_case.status NOT IN('ASSIGNED','ESCALATED') OR v_case.assigned_to<>p_actor_id OR NOT public.audit_export_officer_v1(p_actor_id) THEN RAISE EXCEPTION 'FINANCIAL_EXCEPTION_RESOLUTION_DENIED';END IF;IF UPPER(p_disposition) NOT IN('FALSE_POSITIVE','RECONCILED','REVERSED','REPAIRED','ACCEPTED_RISK','REFERRED') OR LENGTH(BTRIM(COALESCE(p_summary,'')))<10 OR COALESCE(jsonb_object_length(p_evidence),0)=0 THEN RAISE EXCEPTION 'FINANCIAL_EXCEPTION_EVIDENCE_REQUIRED';END IF;UPDATE public.financial_exception_resolution_requests SET status='EXPIRED',updated_at=NOW() WHERE case_id=p_case_id AND status='PENDING' AND expires_at<=NOW();INSERT INTO public.financial_exception_resolution_requests(case_id,requested_by,disposition,summary,evidence) VALUES(p_case_id,p_actor_id,UPPER(p_disposition),BTRIM(p_summary),p_evidence) RETURNING id INTO v_id;UPDATE public.financial_exception_cases SET status='PENDING_APPROVAL',resolution_request_id=v_id,updated_at=NOW() WHERE id=p_case_id;RETURN v_id;END$$;
CREATE OR REPLACE FUNCTION public.respond_financial_exception_resolution_v1(p_reviewer_id TEXT,p_request_id UUID,p_decision TEXT,p_reason TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_r public.financial_exception_resolution_requests%ROWTYPE;v_decision TEXT:=UPPER(BTRIM(p_decision));BEGIN SELECT * INTO v_r FROM public.financial_exception_resolution_requests WHERE id=p_request_id FOR UPDATE;IF NOT FOUND OR v_r.status<>'PENDING' THEN RAISE EXCEPTION 'FINANCIAL_EXCEPTION_RESOLUTION_NOT_OPEN';END IF;IF v_r.expires_at<=NOW() THEN UPDATE public.financial_exception_resolution_requests SET status='EXPIRED',updated_at=NOW() WHERE id=p_request_id;UPDATE public.financial_exception_cases SET status='ASSIGNED',resolution_request_id=NULL,updated_at=NOW() WHERE id=v_r.case_id;RETURN jsonb_build_object('request_id',p_request_id,'status','EXPIRED');END IF;IF NOT public.audit_export_officer_v1(p_reviewer_id) OR p_reviewer_id=v_r.requested_by THEN RAISE EXCEPTION 'FINANCIAL_EXCEPTION_MAKER_CHECKER_REQUIRED';END IF;IF v_decision NOT IN('APPROVE','REJECT') OR LENGTH(BTRIM(COALESCE(p_reason,'')))<10 THEN RAISE EXCEPTION 'FINANCIAL_EXCEPTION_REVIEW_INVALID';END IF;UPDATE public.financial_exception_resolution_requests SET status=CASE WHEN v_decision='APPROVE' THEN 'APPROVED' ELSE 'REJECTED' END,reviewed_by=p_reviewer_id,review_reason=BTRIM(p_reason),reviewed_at=NOW(),updated_at=NOW() WHERE id=p_request_id;UPDATE public.financial_exception_cases SET status=CASE WHEN v_decision='APPROVE' THEN 'RESOLVED' ELSE 'REJECTED' END,resolved_at=CASE WHEN v_decision='APPROVE' THEN NOW() ELSE NULL END,updated_at=NOW() WHERE id=v_r.case_id;RETURN jsonb_build_object('request_id',p_request_id,'case_id',v_r.case_id,'status',CASE WHEN v_decision='APPROVE' THEN 'RESOLVED' ELSE 'REJECTED' END);END$$;
CREATE OR REPLACE FUNCTION public.escalate_overdue_financial_exceptions_v1() RETURNS SETOF public.financial_exception_cases LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$UPDATE public.financial_exception_cases SET status='ESCALATED',escalated_at=NOW(),updated_at=NOW() WHERE status IN('OPEN','ASSIGNED') AND sla_due_at<=NOW() RETURNING *$$;
REVOKE ALL ON FUNCTION public.open_financial_exception_v1(TEXT,TEXT,UUID,TEXT,TEXT,TEXT,JSONB),public.assign_financial_exception_v1(TEXT,UUID,TEXT),public.request_financial_exception_resolution_v1(TEXT,UUID,TEXT,TEXT,JSONB),public.respond_financial_exception_resolution_v1(TEXT,UUID,TEXT,TEXT),public.escalate_overdue_financial_exceptions_v1() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.open_financial_exception_v1(TEXT,TEXT,UUID,TEXT,TEXT,TEXT,JSONB),public.assign_financial_exception_v1(TEXT,UUID,TEXT),public.request_financial_exception_resolution_v1(TEXT,UUID,TEXT,TEXT,JSONB),public.respond_financial_exception_resolution_v1(TEXT,UUID,TEXT,TEXT),public.escalate_overdue_financial_exceptions_v1() TO service_role;
NOTIFY pgrst,'reload schema';
-- END SYNCED MIGRATION: 20260922_financial_exception_workflow.sql
